INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Action 1. Review Excel data', 'Collect and review Excel files for data extracts.', '2019-07-14', 118, 'Address Increasing Annual Costs', 'Not Approved', 'Gathering data');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Action 2', 'Check Data Completeness', '2019-07-14', 118, 'Address Increasing Annual Costs', 'Not Approved', 'Gathering data');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Action 3', 'Request Additional Data', '2019-07-14', 118, 'Address Increasing Annual Costs', 'Not Approved', 'Gathering data');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Review Excel data', 'Collect and review Excel files for data extracts.', '2019-07-14', 118, 'Address Increasing Annual Costs', 'Approved', 'Gathering data');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Second task', 'Detailed description goes here.', '2019-07-14', 118, 'Address Increasing Annual Costs', 'Approved', 'Gathering data');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Action 2: Aggregate data1', 'Get data extracts from different divisions throughout North America', '2019-08-15', 118, 'Address Increasing Annual Costs', 'Not Approved', 'Initial analysis');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Action 3: Perform cluster analysis', 'Create clusters for inventory, wind turbine models, and failures', '2019-08-15', 118, 'Address Increasing Annual Costs', 'Not Approved', 'Initial analysis');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Operational and IOT data review', null, '2019-08-15', 6797, 'Automation 1 assessment', 'Approved', 'Data gathering and review');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Review data completenesss', null, '2019-08-15', 6797, 'Automation 1 assessment', 'Approved', 'Data gathering and review');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Review plant procedures', 'Meet with client to understand standard operating proceedures.', '2019-08-15', 118, 'Address Increasing Annual Costs', 'In Progress', 'Initial analysis');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Review sources of data', 'Review different systems and extracts of automation data', '2019-08-15', 6797, 'Automation 1 assessment', 'Approved', 'Data gathering and review');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Action 1 - Identify outliers abnormalities', 'Identify based on Logical calculation', '2019-09-27', 118, 'Address Increasing Annual Costs', 'Not Approved', 'Further analyses complete');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Review data ommissions', 'Missing data for several fields and periods', '2019-09-27', 118, 'Address Increasing Annual Costs', 'In Progress', 'Further analyses complete');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Review results and establish correlation', 'Review the results in details, all parameters, and explain correlations', '2019-09-27', 118, 'Address Increasing Annual Costs', 'Approved', 'Further analyses complete');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Automate steps for adding new devices', null, '2019-10-18', 6797, 'Automation 1 assessment', 'Approved', 'Analytics and integration automation');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Collect 2017-2018 data for selected sites', null, '2020-03-30', 6799, 'Asset Performance Management - Darwin', 'Approved', 'Asset Performance Monitoring
');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Identify new solutions deployed as outcome of action tracker', null, '2020-03-30', 6799, 'Asset Performance Management - Darwin', 'Approved', 'Asset Performance Monitoring
');
INSERT INTO mvp2.vw_OrderedTasks (title, description, targetDate, projectId, projectTitle, status, milestone) VALUES ('Identify trend in Production / Loss ', null, '2020-03-30', 6799, 'Asset Performance Management - Darwin', 'Approved', 'Asset Performance Monitoring
');